import { getDb } from "../api/queries/connection";
import { users, varieties, listings, reviews, orders } from "./schema";

const db = getDb();

async function seed() {
  console.log("Seeding database...");

  // ─── Seed Users ──────────────────────────────────────────────
  console.log("Seeding users...");
  await db.insert(users).values([
    {
      unionId: "admin_union_001",
      name: "Heritage Admin",
      email: "admin@heritageroots.com",
      role: "admin",
      bio: "Preserving apple diversity since 2020.",
    },
    {
      unionId: "seller_union_001",
      name: "Willow Creek Orchard",
      email: "willow@example.com",
      role: "user",
      location: "Hood River, OR",
      hardinessZone: 7,
      bio: "Family orchard specializing in heritage cider apples. Over 200 varieties on dwarfing rootstock.",
      isVerifiedSeller: true,
      stripeChargesEnabled: true,
      stripePayoutsEnabled: true,
    },
    {
      unionId: "seller_union_002",
      name: "Old Stone Farm",
      email: "oldstone@example.com",
      role: "user",
      location: "Hardwick, VT",
      hardinessZone: 4,
      bio: "Small-scale preservation orchard in the Northeast Kingdom. Certified organic since 2008.",
      isVerifiedSeller: true,
      stripeChargesEnabled: true,
      stripePayoutsEnabled: true,
    },
    {
      unionId: "seller_union_003",
      name: "Blossom Hill Nursery",
      email: "blossom@example.com",
      role: "user",
      location: "Sebastopol, CA",
      hardinessZone: 9,
      bio: "California's premier source for rare apple varieties. We graft to order each spring.",
      isVerifiedSeller: true,
      stripeChargesEnabled: true,
      stripePayoutsEnabled: true,
    },
    {
      unionId: "buyer_union_001",
      name: "Emma Richardson",
      email: "emma@example.com",
      role: "user",
      location: "Ithaca, NY",
      hardinessZone: 5,
      bio: "Home orchardist building a collection of disease-resistant heritage varieties.",
    },
  ]);

  // ─── Seed Varieties ──────────────────────────────────────────
  console.log("Seeding varieties...");
  const varietyData = [
    { name: "Ashmead's Kernel", slug: "ashmeads-kernel", originYear: 1700, originCountry: "England", description: "A classic English russet apple with a distinctive pear-like flavor. Golden-russet skin with rough, sandpaper texture. Flesh is dense, sugary, and aromatic with notes of pear and spice. Excellent for both fresh eating and cider making. Considered one of the finest dessert apples ever bred.", flavorProfile: "Sweet,Tart,Aromatic,Spicy", primaryUse: "Multi-use", skinColor: "Golden russet with rough texture", fleshColor: "Creamy white", diseaseResistance: "Scab resistant, some fire blight resistance", hardinessZoneMin: 5, hardinessZoneMax: 8, parentage: "Unknown seedling", popularity: 95, isRare: true },
    { name: "Roxbury Russet", slug: "roxbury-russet", originYear: 1640, originCountry: "Massachusetts, USA", description: "The oldest known apple variety originating in North America. First cultivated in the Roxbury neighborhood of Boston. Greenish-brown russeted skin with a tart, sweet flavor that improves significantly in storage. A true piece of American agricultural history.", flavorProfile: "Tart,Sweet,Complex", primaryUse: "Multi-use", skinColor: "Greenish-brown russet", fleshColor: "Greenish-white to yellow", diseaseResistance: "Good general disease resistance", hardinessZoneMin: 4, hardinessZoneMax: 8, parentage: "Unknown seedling", popularity: 88, isRare: true },
    { name: "Esopus Spitzenburg", slug: "esopus-spitzenburg", originYear: 1790, originCountry: "New York, USA", description: "One of Thomas Jefferson's favorite apples, grown at Monticello. Deep orange-red with distinctive lenticels. Complex, aromatic flavor with a perfect balance of sweet and tart. A connoisseur's apple that demands perfect growing conditions but rewards the patient orchardist.", flavorProfile: "Sweet,Tart,Aromatic,Complex", primaryUse: "Fresh Eating", skinColor: "Deep orange-red with yellow undertones", fleshColor: "Yellow", diseaseResistance: "Susceptible to cedar apple rust", hardinessZoneMin: 4, hardinessZoneMax: 8, parentage: "Unknown seedling", popularity: 92, isRare: true },
    { name: "Newtown Pippin", slug: "newtown-pippin", originYear: 1759, originCountry: "New York, USA", description: "Originated as a chance seedling in Newtown (now Elmhurst), Queens. Greenish-yellow skin developing a slight blush when fully ripe. Firm, crisp flesh with a pineapple-like flavor when well-ripened. George Washington and Thomas Jefferson both grew this variety. Benjamin Franklin introduced it to England.", flavorProfile: "Sweet,Tart,Pineapple notes", primaryUse: "Multi-use", skinColor: "Greenish-yellow with slight blush", fleshColor: "Creamy white", diseaseResistance: "Good storage qualities", hardinessZoneMin: 5, hardinessZoneMax: 9, parentage: "Chance seedling", popularity: 85, isRare: true },
    { name: "Gravenstein", slug: "gravenstein", originYear: 1669, originCountry: "Denmark", description: "An ancient European variety brought to America by German immigrants. Red and yellow striped skin with some russeting. Tender, juicy flesh with a distinctive sweet-tart flavor. Prized by cooks for its ability to hold shape when baked. Short storage life means it's best enjoyed fresh from the tree.", flavorProfile: "Sweet,Tart,Juicy", primaryUse: "Cooking", skinColor: "Red and yellow striped", fleshColor: "Creamy white", diseaseResistance: "Moderate scab resistance", hardinessZoneMin: 4, hardinessZoneMax: 8, parentage: "Unknown, possibly Italian origin", popularity: 90, isRare: false },
    { name: "Winesap", slug: "winesap", originYear: 1817, originCountry: "New Jersey, USA", description: "An all-American classic with deep crimson, almost wine-colored skin and a distinctive spicy, vinous flavor. The firm, crisp flesh makes it excellent for fresh eating, cooking, and especially cider. One of the most important commercial varieties in American history.", flavorProfile: "Spicy,Vinous,Tart", primaryUse: "Multi-use", skinColor: "Deep crimson to wine-red", fleshColor: "White with yellow tinge", diseaseResistance: "Good general resistance", hardinessZoneMin: 5, hardinessZoneMax: 8, parentage: "Unknown seedling", popularity: 82, isRare: false },
    { name: "Baldwin", slug: "baldwin", originYear: 1740, originCountry: "Massachusetts, USA", description: "Once the most popular apple in New England and the Northeast. Bright red skin with small white dots. Firm, crisp flesh with a sweet-tart flavor that improves in storage. The Baldwin was nearly wiped out by a severe winter in 1934 but has been preserved by dedicated orchardists.", flavorProfile: "Sweet,Tart,Firm", primaryUse: "Fresh Eating", skinColor: "Bright red with white dots", fleshColor: "White to cream", diseaseResistance: "Some scab susceptibility", hardinessZoneMin: 4, hardinessZoneMax: 8, parentage: "Unknown seedling, Lowell area", popularity: 78, isRare: true },
    { name: "Northern Spy", slug: "northern-spy", originYear: 1800, originCountry: "New York, USA", description: "The ultimate pie apple. Large, round fruit with pale green-yellow skin and red stripes. White, crisp flesh holds its shape perfectly when baked while delivering a complex sweet-tart flavor. Takes longer to bear fruit than most varieties but rewards patience with exceptional quality.", flavorProfile: "Tart,Sweet,Firm,Complex", primaryUse: "Cooking", skinColor: "Pale green-yellow with red stripes", fleshColor: "White and crisp", diseaseResistance: "Good fire blight resistance", hardinessZoneMin: 3, hardinessZoneMax: 8, parentage: "Unknown seedling, East Bloomfield, NY", popularity: 80, isRare: false },
    { name: "Arkansas Black", slug: "arkansas-black", originYear: 1870, originCountry: "Arkansas, USA", description: "A stunning storage apple that darkens to an almost black-purple color in storage. Originated in Benton County, Arkansas. Dense, hard flesh with a rich, sweet flavor that develops complexity after months in cold storage. A favorite among apple collectors for its dramatic appearance.", flavorProfile: "Sweet,Rich,Dense", primaryUse: "Storage", skinColor: "Deep red to almost black", fleshColor: "Creamy yellow", diseaseResistance: "Good general resistance", hardinessZoneMin: 5, hardinessZoneMax: 8, parentage: "Winesap seedling", popularity: 75, isRare: true },
    { name: "Cox's Orange Pippin", slug: "coxs-orange-pippin", originYear: 1825, originCountry: "England", description: "Widely regarded as the finest dessert apple in the world. Orange-red skin with red stripes over a golden background. The flesh is aromatic with an incomparable complex flavor often described as having notes of cherry, anise, and orange. Requires careful cultivation but is worth every effort.", flavorProfile: "Aromatic,Complex,Sweet-Tart", primaryUse: "Fresh Eating", skinColor: "Orange-red with red stripes", fleshColor: "Creamy yellow", diseaseResistance: "Susceptible to scab and canker", hardinessZoneMin: 5, hardinessZoneMax: 9, parentage: "Ribston Pippin x unknown", popularity: 93, isRare: true },
    { name: "Calville Blanc d'Hiver", slug: "calville-blanc-dhiver", originYear: 1598, originCountry: "France", description: "One of the oldest known apple varieties still in cultivation. Mentioned in French literature as early as 1598. Lumpy, irregular shape with pale yellow skin flushed with pink. The high vitamin C content and tart flavor make it exceptional for cooking, especially French apple tarts.", flavorProfile: "Tart,Aromatic,Vitamin-rich", primaryUse: "Cooking", skinColor: "Pale yellow with pink blush", fleshColor: "White", diseaseResistance: "Moderate resistance", hardinessZoneMin: 5, hardinessZoneMax: 9, parentage: "Unknown, ancient French variety", popularity: 72, isRare: true },
    { name: "Reine des Reinettes", slug: "reine-des-reinettes", originYear: 1770, originCountry: "France", description: "The 'Queen of the Pippins' is an elegant French variety with orange-red skin and fine russet dots. The flesh is firm, crisp, and richly flavored with a perfect balance of sweetness and acidity. Excellent for both fresh eating and cider production. A favorite of French cidermakers.", flavorProfile: "Sweet,Tart,Balanced,Rich", primaryUse: "Multi-use", skinColor: "Orange-red with russet dots", fleshColor: "Yellowish", diseaseResistance: "Good general resistance", hardinessZoneMin: 5, hardinessZoneMax: 9, parentage: "Unknown, possibly Orange Pippin", popularity: 68, isRare: true },
    { name: "Pink Pearl", slug: "pink-pearl", originYear: 1944, originCountry: "California, USA", description: "A stunning surprise apple with ordinary yellow-green skin that conceals brilliant pink flesh. Developed by Albert Etter in Northern California. The flesh is crisp and tart with a distinctive berry-like flavor. A showstopper in salads, pies, and especially pink applesauce.", flavorProfile: "Tart,Berry notes,Crisp", primaryUse: "Fresh Eating", skinColor: "Yellow-green", fleshColor: "Brilliant pink", diseaseResistance: "Good scab resistance", hardinessZoneMin: 5, hardinessZoneMax: 9, parentage: "Surprise x unknown", popularity: 87, isRare: true },
    { name: "Hidden Rose", slug: "hidden-rose", originYear: 1960, originCountry: "Oregon, USA", description: "Discovered as a chance seedling in Airlie, Oregon. Similar to Pink Pearl but with an even deeper rose-colored flesh. The flavor is sweet-tart with tropical notes. Originally called 'Airlie Red Flesh,' this variety has gained cult status among apple enthusiasts for its stunning interior.", flavorProfile: "Sweet,Tart,Tropical notes", primaryUse: "Fresh Eating", skinColor: "Yellow with slight blush", fleshColor: "Deep rose pink", diseaseResistance: "Moderate resistance", hardinessZoneMin: 6, hardinessZoneMax: 9, parentage: "Chance seedling", popularity: 83, isRare: true },
    { name: "Liberty", slug: "liberty", originYear: 1955, originCountry: "New York, USA", description: "Developed by the New York State Agricultural Experiment Station as a disease-resistant variety. Dark red skin with a McIntosh-like appearance. Crisp, juicy flesh with a well-balanced sweet-tart flavor. One of the best disease-resistant varieties available, requiring minimal spray.", flavorProfile: "Sweet,Tart,Juicy,Crisp", primaryUse: "Fresh Eating", skinColor: "Dark red", fleshColor: "White to cream", diseaseResistance: "Immune to apple scab, resistant to fire blight and cedar apple rust", hardinessZoneMin: 4, hardinessZoneMax: 8, parentage: "Macoun x Purdue 54-12", popularity: 91, isRare: false },
    { name: "GoldRush", slug: "goldrush", originYear: 1972, originCountry: "Indiana, USA", description: "A modern variety that captures old-world flavor with new-world disease resistance. Golden-yellow skin with a slight blush. Dense, crisp flesh with a complex spicy-sweet flavor that only improves after months in storage. Can keep until June without refrigeration in proper root cellar conditions.", flavorProfile: "Spicy,Sweet,Complex,Crisp", primaryUse: "Storage", skinColor: "Golden-yellow with blush", fleshColor: "Pale yellow", diseaseResistance: "Immune to scab, resistant to powdery mildew", hardinessZoneMin: 5, hardinessZoneMax: 8, parentage: "Golden Delicious x Co-op 17", popularity: 84, isRare: false },
    { name: "Zestar!", slug: "zestar", originYear: 1999, originCountry: "Minnesota, USA", description: "The earliest excellent apple from the University of Minnesota breeding program. Red over yellow with a distinctive crunchy texture and brown sugar sweetness. Ripens in August, weeks before most varieties. Remarkably crisp for an early apple with a storage life of 2 months.", flavorProfile: "Sweet,Brown sugar notes,Crisp", primaryUse: "Fresh Eating", skinColor: "Red over yellow", fleshColor: "White", diseaseResistance: "Good general resistance", hardinessZoneMin: 3, hardinessZoneMax: 8, parentage: "State Fair x MN 1691", popularity: 86, isRare: false },
    { name: "Honeycrisp", slug: "honeycrisp", originYear: 1960, originCountry: "Minnesota, USA", description: "The apple that changed the industry. Explosively crisp texture with a perfect sweet-tart balance and honeyed undertones. The cells in the flesh are unusually large, creating a juiciness that bursts with each bite. Now one of the most widely grown varieties in North America.", flavorProfile: "Sweet,Tart,Honey notes,Explosively crisp", primaryUse: "Fresh Eating", skinColor: "Red over yellow-green", fleshColor: "White", diseaseResistance: "Moderate disease resistance", hardinessZoneMin: 3, hardinessZoneMax: 8, parentage: "Macoun x Honeygold", popularity: 99, isRare: false },
    { name: "Chestnut Crab", slug: "chestnut-crab", originYear: 1946, originCountry: "Minnesota, USA", description: "The finest crab apple for fresh eating. Russeted golden skin with red blush. Small in size but enormous in flavor — intensely sweet with complex nutty undertones reminiscent of chestnuts. Perfect for ornamental landscaping, pollinating other varieties, and eating out of hand.", flavorProfile: "Sweet,Nutty,Complex,Intense", primaryUse: "Fresh Eating", skinColor: "Golden russet with red blush", fleshColor: "Creamy yellow", diseaseResistance: "Very hardy, disease resistant", hardinessZoneMin: 3, hardinessZoneMax: 8, parentage: "Malinda x unknown crab", popularity: 77, isRare: false },
    { name: "Kingston Black", slug: "kingston-black", originYear: 1820, originCountry: "England", description: "The holy grail of English cider apples. Small, dark red to almost black fruit with bittersharp juice that produces complex, tannic ciders. Nearly extinct in the 1970s until rediscovered by cider enthusiasts. Essential for traditional English-style cider production.", flavorProfile: "Bittersharp,Tannic,Complex", primaryUse: "Cider", skinColor: "Dark red to black", fleshColor: "White tinged with pink", diseaseResistance: "Moderate resistance", hardinessZoneMin: 5, hardinessZoneMax: 8, parentage: "Unknown, Somerset England", popularity: 89, isRare: true },
    { name: "Dabinett", slug: "dabinett", originYear: 1900, originCountry: "England", description: "A classic English bittersweet cider apple from Somerset. Small, golden-yellow fruit with russet dots. The juice is rich in tannins and low in acid, producing full-bodied, complex ciders that improve with age. Self-fertile and a reliable cropper, making it popular with cidermakers.", flavorProfile: "Bittersweet,Tannic,Rich", primaryUse: "Cider", skinColor: "Golden-yellow with russet", fleshColor: "Creamy white", diseaseResistance: "Good general resistance", hardinessZoneMin: 5, hardinessZoneMax: 9, parentage: "Unknown, Somerset England", popularity: 81, isRare: true },
    { name: "Black Oxford", slug: "black-oxford", originYear: 1790, originCountry: "Maine, USA", description: "A remarkable Maine heirloom that develops a deep purple-black color in storage. The firm, white flesh has a sweet, mildly tart flavor that improves for months after harvest. Extremely hardy and disease resistant — a perfect choice for organic growers in cold climates.", flavorProfile: "Sweet,Mild tart,Firm", primaryUse: "Storage", skinColor: "Deep purple-black", fleshColor: "White", diseaseResistance: "Excellent disease resistance", hardinessZoneMin: 4, hardinessZoneMax: 7, parentage: "Unknown, Paris, Maine", popularity: 70, isRare: true },
    { name: "Blue Pearmain", slug: "blue-pearmain", originYear: 1750, originCountry: "New England, USA", description: "A large, handsome apple with distinctive blue-purple bloom over deep red skin. The yellow flesh is firm, fine-textured, and richly flavored with a perfect balance of sweet and acid. Once common throughout New England, now rare and sought after by collectors.", flavorProfile: "Rich,Sweet-Tart,Balanced", primaryUse: "Fresh Eating", skinColor: "Blue-purple bloom over red", fleshColor: "Yellow", diseaseResistance: "Good general resistance", hardinessZoneMin: 4, hardinessZoneMax: 8, parentage: "Unknown, possibly English origin", popularity: 66, isRare: true },
    { name: "Hudson's Golden Gem", slug: "hudsons-golden-gem", originYear: 1930, originCountry: "Oregon, USA", description: "A tall, pear-shaped apple with golden-yellow skin and a distinctive elongated form. The flesh is crisp, juicy, and honey-sweet with pear-like aromatics. One of the best fresh-eating apples for Pacific Northwest conditions. Developed from a chance seedling found along a fence row.", flavorProfile: "Sweet,Honey,Pear notes,Juicy", primaryUse: "Fresh Eating", skinColor: "Golden-yellow", fleshColor: "Pale yellow", diseaseResistance: "Moderate resistance", hardinessZoneMin: 5, hardinessZoneMax: 8, parentage: "Chance seedling", popularity: 73, isRare: true },
    { name: "Rubinette", slug: "rubinette", originYear: 1966, originCountry: "Switzerland", description: "A Swiss masterpiece that combines the sweetness of Golden Delicious with the complexity of Cox's Orange Pippin. Small to medium fruit with orange-red striping over golden skin. The flesh is dense, crisp, and intensely flavored — a true connoisseur's apple that rivals the best English varieties.", flavorProfile: "Intense,Complex,Sweet-Tart,Crisp", primaryUse: "Fresh Eating", skinColor: "Orange-red over golden", fleshColor: "Creamy yellow", diseaseResistance: "Some scab susceptibility", hardinessZoneMin: 5, hardinessZoneMax: 8, parentage: "Golden Delicious x Cox's Orange Pippin", popularity: 76, isRare: true },
    { name: "Stayman Winesap", slug: "stayman-winesap", originYear: 1866, originCountry: "Kansas, USA", description: "A superior strain of Winesap with larger fruit and more complex flavor. The deep red skin conceals firm, crisp flesh with a distinctive spicy, wine-like tang. A triploid variety that produces pollen but needs another pollinator. Excellent for eating, cooking, and cider.", flavorProfile: "Spicy,Wine-like,Tart,Complex", primaryUse: "Multi-use", skinColor: "Deep red", fleshColor: "Greenish-white", diseaseResistance: "Good general resistance", hardinessZoneMin: 5, hardinessZoneMax: 8, parentage: "Winesap seedling", popularity: 79, isRare: false },
    { name: "Freedom", slug: "freedom", originYear: 1958, originCountry: "New York, USA", description: "Developed by the New York State Agricultural Experiment Station as a highly disease-resistant variety. Red-striped skin over pale yellow. The flesh is crisp and juicy with a pleasant mild flavor. Designed for organic growers who need reliable crops without extensive spray programs.", flavorProfile: "Mild,Sweet-Tart,Juicy,Crisp", primaryUse: "Fresh Eating", skinColor: "Red-striped over pale yellow", fleshColor: "White", diseaseResistance: "Immune to scab, resistant to fire blight and cedar apple rust", hardinessZoneMin: 4, hardinessZoneMax: 8, parentage: "Macoun x Antonovka x other", popularity: 71, isRare: false },
    { name: "Enterprise", slug: "enterprise", originYear: 1982, originCountry: "Illinois, USA", description: "A modern disease-resistant apple with excellent storage qualities. Dark red, glossy skin with a uniform appearance. The flesh is dense, crisp, and moderately tart with a flavor that improves after storage. One of the best commercial varieties for organic production.", flavorProfile: "Tart,Crisp,Improves in storage", primaryUse: "Storage", skinColor: "Dark red, glossy", fleshColor: "Creamy white", diseaseResistance: "Immune to scab, resistant to fire blight and cedar apple rust", hardinessZoneMin: 4, hardinessZoneMax: 8, parentage: "PRI breeding program", popularity: 74, isRare: false },
    { name: "Pristine", slug: "pristine", originYear: 1982, originCountry: "Indiana, USA", description: "An early-ripening disease-resistant variety from the PRI breeding program. Attractive yellow-green skin with a slight blush. The flesh is crisp and juicy with a well-balanced sweet-tart flavor. Ripens in mid-July, making it one of the earliest quality apples available.", flavorProfile: "Sweet-Tart,Juicy,Crisp,Early", primaryUse: "Fresh Eating", skinColor: "Yellow-green with blush", fleshColor: "White", diseaseResistance: "Immune to scab, resistant to fire blight", hardinessZoneMin: 5, hardinessZoneMax: 8, parentage: "Camuzat x unknown", popularity: 69, isRare: false },
    { name: "Sweet Sixteen", slug: "sweet-sixteen", originYear: 1977, originCountry: "Minnesota, USA", description: "A unique northern variety with an unusual cherry-candy flavor. Red and yellow striped skin with a glossy finish. The flesh is crisp and distinctly flavored with notes of cherry, vanilla, and licorice. Extremely hardy, surviving temperatures to -40°F. A favorite among cold-climate growers.", flavorProfile: "Cherry candy,Sweet,Unique,Crisp", primaryUse: "Fresh Eating", skinColor: "Red and yellow striped", fleshColor: "White", diseaseResistance: "Good general resistance, very hardy", hardinessZoneMin: 3, hardinessZoneMax: 8, parentage: "MN 447 x Northern Spy", popularity: 82, isRare: false },
    { name: "Keepsake", slug: "keepsake", originYear: 1978, originCountry: "Minnesota, USA", description: "The parent of Honeycrisp, sharing that distinctive crisp texture but with a more complex, honeyed flavor. Golden-orange skin with a red blush. The dense flesh stores incredibly well — properly kept, it lasts until May. One of the finest storage apples for northern climates.", flavorProfile: "Honeyed,Sweet,Complex,Crisp", primaryUse: "Storage", skinColor: "Golden-orange with red blush", fleshColor: "Pale yellow", diseaseResistance: "Good general resistance, very hardy", hardinessZoneMin: 3, hardinessZoneMax: 8, parentage: "Frostbite x Northern Spy", popularity: 78, isRare: false },
    { name: "Redfield", slug: "redfield", originYear: 1938, originCountry: "New York, USA", description: "Developed specifically for the New York cider industry. The red flesh produces a distinctive rosy cider with rich tannins and complex flavor. Large fruit with deep red skin that matches its crimson flesh. A specialty variety for artisanal cidermakers seeking unique products.", flavorProfile: "Tannic,Rich,Bittersweet", primaryUse: "Cider", skinColor: "Deep red", fleshColor: "Red to pink", diseaseResistance: "Moderate resistance", hardinessZoneMin: 4, hardinessZoneMax: 8, parentage: "Wolf River x Niedzwetzkyana", popularity: 65, isRare: true },
    { name: "Yarlington Mill", slug: "yarlington-mill", originYear: 1900, originCountry: "England", description: "A legendary English cider apple from Somerset, named after the mill where it was discovered. Produces a full bittersweet juice with excellent body and complex aromatics. A biennial bearer that crops heavily in alternate years. Essential for traditional English cider blends.", flavorProfile: "Bittersweet,Tannic,Full-bodied", primaryUse: "Cider", skinColor: "Yellow-green with red flush", fleshColor: "Creamy", diseaseResistance: "Good general resistance", hardinessZoneMin: 5, hardinessZoneMax: 9, parentage: "Unknown, Yarlington, Somerset", popularity: 67, isRare: true },
    { name: "Tremlett's Bitter", slug: "tremletts-bitter", originYear: 1900, originCountry: "England", description: "A classic English bittersweet cider apple with high tannin content and low acidity. Small to medium fruit with red and yellow skin. The juice produces rich, astringent ciders that age beautifully. Named after the Tremlett family who popularized it in Devon.", flavorProfile: "Bittersweet,High tannin,Astringent", primaryUse: "Cider", skinColor: "Red and yellow", fleshColor: "White", diseaseResistance: "Good general resistance", hardinessZoneMin: 5, hardinessZoneMax: 8, parentage: "Unknown, Devon England", popularity: 63, isRare: true },
    { name: "Opal", slug: "opal", originYear: 1999, originCountry: "Czech Republic", description: "A modern European variety with striking lemon-yellow skin and distinctive crisp texture. The flesh is juicy with a honey-sweet flavor and low acidity. A cross between Golden Delicious and Topaz that combines the best traits of both parents. Excellent disease resistance and reliable cropping.", flavorProfile: "Sweet,Honey,Low acid,Crisp", primaryUse: "Fresh Eating", skinColor: "Lemon-yellow", fleshColor: "Pale yellow", diseaseResistance: "Good scab and powdery mildew resistance", hardinessZoneMin: 5, hardinessZoneMax: 8, parentage: "Golden Delicious x Topaz", popularity: 72, isRare: false },
    { name: "Jonagold", slug: "jonagold", originYear: 1953, originCountry: "New York, USA", description: "A beloved commercial and backyard variety combining the best of Jonathan and Golden Delicious. Large, attractive fruit with red blush over golden-yellow skin. The flesh is crisp, juicy, and honey-sweet with a refreshing tartness. A triploid that produces large, beautiful apples consistently.", flavorProfile: "Honey-sweet,Tart,Juicy,Crisp", primaryUse: "Fresh Eating", skinColor: "Red blush over golden-yellow", fleshColor: "Creamy yellow", diseaseResistance: "Moderate disease resistance", hardinessZoneMin: 5, hardinessZoneMax: 8, parentage: "Jonathan x Golden Delicious", popularity: 88, isRare: false },
    { name: "Medaille d'Or", slug: "medaille-dor", originYear: 1860, originCountry: "France", description: "A distinguished French cider apple that has won numerous awards for its exceptional juice quality. Small, golden-russet fruit with a distinctive aroma. Produces a full-bodied, bittersweet cider with complex floral and honey notes. Slow to bear but worth the wait for serious cidermakers.", flavorProfile: "Bittersweet,Floral,Honey notes,Complex", primaryUse: "Cider", skinColor: "Golden russet", fleshColor: "Pale yellow", diseaseResistance: "Moderate resistance", hardinessZoneMin: 5, hardinessZoneMax: 9, parentage: "Unknown, Normandy France", popularity: 61, isRare: true },
    { name: "Michelin", slug: "michelin", originYear: 1870, originCountry: "France", description: "One of the most widely planted cider varieties in Normandy. Produces a reliable crop of small, greenish-yellow fruit with bittersweet juice. The cider is smooth, well-balanced, and blends beautifully with sharper varieties. A cornerstone of French cider production for over 150 years.", flavorProfile: "Bittersweet,Smooth,Balanced", primaryUse: "Cider", skinColor: "Greenish-yellow", fleshColor: "White", diseaseResistance: "Good general resistance", hardinessZoneMin: 5, hardinessZoneMax: 9, parentage: "Unknown, Normandy France", popularity: 64, isRare: true },
    { name: "SnowSweet", slug: "snowsweet", originYear: 2002, originCountry: "Minnesota, USA", description: "A relatively new variety from the University of Minnesota with outstanding winter hardiness. Deep red skin with a snow-white flesh that resists browning when cut — perfect for fruit trays and salads. The flavor is sweet and slightly tart with hints of butterscotch.", flavorProfile: "Sweet,Butterscotch,Low browning", primaryUse: "Fresh Eating", skinColor: "Deep red", fleshColor: "Snow white", diseaseResistance: "Good general resistance", hardinessZoneMin: 4, hardinessZoneMax: 8, parentage: "Connie x unknown", popularity: 70, isRare: false },
    { name: "Harry Masters Jersey", slug: "harry-masters-jersey", originYear: 1900, originCountry: "England", description: "A highly regarded English bittersweet cider apple from Somerset. Small fruit with red streaks over yellow skin. The juice is rich in tannins with low acidity, producing full-flavored ciders that develop beautifully with age. Named after a local farmer who championed its cultivation.", flavorProfile: "Bittersweet,Rich tannin,Full-flavored", primaryUse: "Cider", skinColor: "Red streaks over yellow", fleshColor: "Creamy", diseaseResistance: "Good general resistance", hardinessZoneMin: 5, hardinessZoneMax: 8, parentage: "Unknown, Somerset England", popularity: 62, isRare: true },
  ];

  await db.insert(varieties).values(varietyData);

  // ─── Seed Listings ───────────────────────────────────────────
  console.log("Seeding listings...");
  await db.insert(listings).values([
    { sellerId: 2, varietyId: 1, quantity: 12, pricePerStick: "18.00", description: "Premium Ashmead's Kernel scions from our 40-year-old mother tree. Excellent grafting wood, harvested February 2025. Will include grafting tape and basic instructions.", shippingZones: "4,5,6,7,8", status: "active", harvestDate: new Date("2025-02-15") },
    { sellerId: 2, varietyId: 2, quantity: 8, pricePerStick: "20.00", description: "Authentic Roxbury Russet from our preservation block. These scions are from verified original stock. Limited quantity available.", shippingZones: "3,4,5,6,7", status: "active", harvestDate: new Date("2025-02-10") },
    { sellerId: 2, varietyId: 8, quantity: 15, pricePerStick: "15.00", description: "Northern Spy scions — the ultimate pie apple. Robust wood from mature trees. Good for beginners to practice grafting.", shippingZones: "3,4,5,6,7,8", status: "active", harvestDate: new Date("2025-02-20") },
    { sellerId: 2, varietyId: 16, quantity: 20, pricePerStick: "12.00", description: "Liberty scions from our disease-resistant block. Perfect for organic growers. Heavy bearing, reliable variety.", shippingZones: "4,5,6,7,8", status: "active", harvestDate: new Date("2025-02-18") },
    { sellerId: 2, varietyId: 17, quantity: 10, pricePerStick: "16.00", description: "GoldRush scions — exceptional storage quality. The flavor only improves after months in the cellar. From our best-performing tree.", shippingZones: "5,6,7,8", status: "active", harvestDate: new Date("2025-02-12") },
    { sellerId: 3, varietyId: 3, quantity: 6, pricePerStick: "22.00", description: "Esopus Spitzenburg — Thomas Jefferson's favorite apple. Rare and highly sought after. Scions from our heritage block in Vermont.", shippingZones: "4,5,6,7", status: "active", harvestDate: new Date("2025-02-14") },
    { sellerId: 3, varietyId: 5, quantity: 18, pricePerStick: "14.00", description: "Gravenstein scions from our organic orchard. Excellent cooking apple, perfect for pies and sauce. Early season variety.", shippingZones: "4,5,6,7,8", status: "active", harvestDate: new Date("2025-02-22") },
    { sellerId: 3, varietyId: 7, quantity: 9, pricePerStick: "19.00", description: "Baldwin — once the king of New England apples. Rare heritage variety from verified old stock. Limited supply.", shippingZones: "3,4,5,6,7", status: "active", harvestDate: new Date("2025-02-16") },
    { sellerId: 3, varietyId: 19, quantity: 14, pricePerStick: "17.00", description: "Kingston Black — the holy grail of cider apples. Essential for traditional English-style cider. From our cider block.", shippingZones: "4,5,6,7,8", status: "active", harvestDate: new Date("2025-02-19") },
    { sellerId: 3, varietyId: 21, quantity: 11, pricePerStick: "15.00", description: "Black Oxford scions — extremely hardy Maine heirloom. The deep purple-black color develops in storage. Perfect for cold climates.", shippingZones: "3,4,5,6,7", status: "active", harvestDate: new Date("2025-02-21") },
    { sellerId: 4, varietyId: 4, quantity: 7, pricePerStick: "24.00", description: "Newtown Pippin — Benjamin Franklin's gift to England. Complex flavor with pineapple notes when well-ripened. Premium scions from California.", shippingZones: "5,6,7,8,9", status: "active", harvestDate: new Date("2025-02-13") },
    { sellerId: 4, varietyId: 13, quantity: 10, pricePerStick: "20.00", description: "Pink Pearl — the showstopper apple with brilliant pink flesh. Perfect for pink applesauce and stunning in salads. California-grown.", shippingZones: "5,6,7,8,9", status: "active", harvestDate: new Date("2025-02-17") },
    { sellerId: 4, varietyId: 14, quantity: 8, pricePerStick: "21.00", description: "Hidden Rose — even deeper pink flesh than Pink Pearl. Sweet-tart with tropical notes. A collector's favorite from the Pacific Northwest.", shippingZones: "6,7,8,9", status: "active", harvestDate: new Date("2025-02-11") },
    { sellerId: 4, varietyId: 18, quantity: 25, pricePerStick: "14.00", description: "Honeycrisp scions from our California test block. Explosively crisp texture with honeyed sweetness. Reliable bearer.", shippingZones: "5,6,7,8,9", status: "active", harvestDate: new Date("2025-02-20") },
    { sellerId: 4, varietyId: 20, quantity: 12, pricePerStick: "16.00", description: "Dabinett — classic English bittersweet cider apple. Rich in tannins, produces full-bodied cider. From our Sonoma cider block.", shippingZones: "5,6,7,8,9", status: "active", harvestDate: new Date("2025-02-15") },
  ]);

  // ─── Seed Orders ─────────────────────────────────────────────
  console.log("Seeding orders...");
  await db.insert(orders).values([
    { buyerId: 5, sellerId: 2, listingId: 1, varietyName: "Ashmead's Kernel", quantity: 3, pricePerStick: "18.00", totalAmount: "54.00", platformFee: "8.10", sellerPayout: "45.90", status: "delivered", shippingAddress: "42 Orchard Lane, Ithaca, NY 14850" },
    { buyerId: 5, sellerId: 2, listingId: 3, varietyName: "Northern Spy", quantity: 5, pricePerStick: "15.00", totalAmount: "75.00", platformFee: "11.25", sellerPayout: "63.75", status: "delivered", shippingAddress: "42 Orchard Lane, Ithaca, NY 14850" },
    { buyerId: 5, sellerId: 3, listingId: 6, varietyName: "Esopus Spitzenburg", quantity: 2, pricePerStick: "22.00", totalAmount: "44.00", platformFee: "6.60", sellerPayout: "37.40", status: "shipped", shippingAddress: "42 Orchard Lane, Ithaca, NY 14850" },
    { buyerId: 5, sellerId: 4, listingId: 12, varietyName: "Pink Pearl", quantity: 4, pricePerStick: "20.00", totalAmount: "80.00", platformFee: "12.00", sellerPayout: "68.00", status: "confirmed", shippingAddress: "42 Orchard Lane, Ithaca, NY 14850" },
  ]);

  // ─── Seed Reviews ────────────────────────────────────────────
  console.log("Seeding reviews...");
  await db.insert(reviews).values([
    { orderId: 1, reviewerId: 5, sellerId: 2, rating: 5, comment: "Excellent scions! All three grafts took successfully. Willow Creek Orchard sent beautifully prepared wood with clear instructions. Will definitely order again." },
    { orderId: 2, reviewerId: 5, sellerId: 2, rating: 5, comment: "Northern Spy scions were perfect — fresh cut ends showing green cambium. Fast shipping, well packaged in damp paper. 4 out of 5 grafts thriving!" },
    { orderId: 1, reviewerId: 5, sellerId: 2, rating: 4, comment: "Great quality scion wood. The Ashmead's Kernel is already pushing buds. Shipping was quick. Would appreciate more detailed grafting instructions for beginners." },
    { orderId: 2, reviewerId: 5, sellerId: 2, rating: 5, comment: "Old Stone Farm is the real deal. Verified heritage stock, organic practices, and you can tell they care about preservation. My go-to source for rare varieties." },
    { orderId: 3, reviewerId: 5, sellerId: 3, rating: 5, comment: "Esopus Spitzenburg arrived in perfect condition. The seller included a handwritten note about the variety's history at Monticello — lovely touch!" },
    { orderId: 3, reviewerId: 5, sellerId: 3, rating: 4, comment: "Good scions, well packaged. Took a bit longer to ship than expected but the wood was still fresh. One graft failed but that could be my technique." },
    { orderId: 4, reviewerId: 5, sellerId: 4, rating: 5, comment: "Pink Pearl scions from Blossom Hill were incredible — all four grafts thriving! The deep pink flesh is going to be stunning. California quality shows." },
    { orderId: 4, reviewerId: 5, sellerId: 4, rating: 5, comment: "Beautifully packed with ice packs to keep the scions cool during transit. Very professional operation. Already placed another order for Hidden Rose!" },
  ]);

  console.log("Seeding complete!");
}

seed().catch(console.error);
